### ISSUE TITLE
Admin API not Provisioned without Enabling Eneterprise

### ISSUE THREAD

**Issue by lorenzoaiello** [Kong/kong-terraform-aws#15]
The docs say:

```
HTTP:80 - Kong Proxy
HTTPS:443 - Kong Proxy
HTTPS:8444 - Kong Admin API
HTTPS:8445 - Kong Manager (Enterprise Edition only)
HTTPS:8446 - Kong Dev Portal GUI (Enterprise Edition only)
HTTPS:8447 - Kong Dev Portal API (Enterprise Edition only)
```

But only the Kong Proxy ports are configured unless `var.enable_ee=true` which means the Kong Admin API is inaccessible.

**Comment by DennoVonDiesel** [comment]
The Admin API is only exposed externally when Enterprise is enabled since it is protected with RBAC and authentication/authorized. Otherwise it is, and should only be, exposed to localhost for security reasons. I've updated the documentation to reflect this.  Thanks!
