### ISSUE TITLE
Need to skip resources which have already been created

### ISSUE THREAD

**Issue by degui-xu** [Kong/kong-terraform-aws#2]
Error: Error creating IAM Role kong-demo: EntityAlreadyExists: Role with name kong-demo already exists.
	status code: 409, request id: afc89ee0-8f85-4933-9df5-0cdc95511ccf

  on iam.tf line 36, in resource "aws_iam_role" "kong":
  36: resource "aws_iam_role" "kong" {

Error: Error creating DB Parameter Group: DBParameterGroupAlreadyExists: Parameter group kong-demo already exists
	status code: 400, request id: 44502f7b-4069-4024-8ffb-6c2fa9fc72c5

  on rds.tf line 39, in resource "aws_db_parameter_group" "kong":
  39: resource "aws_db_parameter_group" "kong" {

Error: Error creating Security Group: InvalidGroup.Duplicate: The security group 'kong-demo-redis' already exists for VPC 'vpc-dd18fcb8'
	status code: 400, request id: 39e69048-7067-4cfc-b79c-3e2f6a7f1d76

  on security.tf line 41, in resource "aws_security_group" "redis":
  41: resource "aws_security_group" "redis" {

Error: Error creating Security Group: InvalidGroup.Duplicate: The security group 'kong-demo' already exists for VPC 'vpc-dd18fcb8'
	status code: 400, request id: 9f01db05-2c16-4c7c-9a28-f9a746d976f7

  on security.tf line 80, in resource "aws_security_group" "kong":
  80: resource "aws_security_group" "kong" {

Error: Error creating Security Group: InvalidGroup.Duplicate: The security group 'kong-demo-internal-lb' already exists for VPC 'vpc-dd18fcb8'
	status code: 400, request id: 68cb6651-5390-4b0e-bdd3-08414babb06d

  on security.tf line 268, in resource "aws_security_group" "internal-lb":
 268: resource "aws_security_group" "internal-lb" {

Error: error creating SSM parameter: ParameterAlreadyExists: The parameter already exists. To overwrite this value, set the overwrite option in the request to true.
	status code: 400, request id: 6aa10cc3-5339-4daa-bd7b-c5687a6bba6c

  on ssm.tf line 66, in resource "aws_ssm_parameter" "db-name":
  66: resource "aws_ssm_parameter" "db-name" {

Error: Error creating Cache Parameter Group: CacheParameterGroupAlreadyExists: Parameter group kong-demo already exists
	status code: 400, request id: 93fee194-e934-45fe-9fb2-8a026d9f5deb

  on .terraform/modules/kong/redis.tf line 28, in resource "aws_elasticache_parameter_group" "kong":
  28: resource "aws_elasticache_parameter_group" "kong" {

Error: Error creating Security Group: InvalidGroup.Duplicate: The security group 'kong-demo-postgresql' already exists for VPC 'vpc-dd18fcb8'
	status code: 400, request id: 7277173c-81da-4878-9470-9aa0a26f8796

  on .terraform/modules/kong/security.tf line 2, in resource "aws_security_group" "postgresql":
   2: resource "aws_security_group" "postgresql" {

Error: Error creating Security Group: InvalidGroup.Duplicate: The security group 'kong-demo-external-lb' already exists for VPC 'vpc-dd18fcb8'
	status code: 400, request id: e4f2787f-5047-473e-bb36-3ee3c95d9594

  on .terraform/modules/kong/security.tf line 218, in resource "aws_security_group" "external-lb":
 218: resource "aws_security_group" "external-lb" {

Error: AlreadyExistsException: An alias with the name arn:aws:kms:ap-southeast-1:151743893450:alias/kong-demo already exists
	status code: 400, request id: ac2ca03d-9a68-4f9d-8dab-1f5612d1a039

  on .terraform/modules/kong/ssm.tf line 15, in resource "aws_kms_alias" "kong":
  15: resource "aws_kms_alias" "kong" {

**Comment by DennoVonDiesel** [comment]
t looks like someone already created a Kong cluster using the module with the environment "demo" in this account/VPC outside of the current VPC state. The simplest solution would be to set environment = demo-2 or something meaningful to you to avoid duplicate resources. Alternatively you can find the terraform state and "terraform destroy" the module before recreating it with the same name. Let me know if this helps!

**Comment by degui-xu** [comment]
I tested again and changed the environment to "dxu-201911" to make sure it's unique. But I am still getting the same errors.

**Comment by DennoVonDiesel** [comment]
This was the result of setting up a terraform root module inside of this cloned repository, resulting in duplication of resources. We created a new directory for his main.tf and referenced the module per the documentation and it's working.

**Comment by snabar** [comment]
@DennoVonDiesel @degui-xu could you please explain what's the correct way to reference the module? Where can I find the documentation you reference above? I am running into the exact same issue.
