### ISSUE TITLE
port 8001 not listening internally for LB

### ISSUE THREAD

**Issue by miketwenty1** [Kong/kong-terraform-aws#25]
Was it intended to NOT expose/listen for the admin port on the internal load balancer?
If I have a service that needs to use Kong's admin API, which methods do you suggest, for that service to contact the kong ec2 instance on port 8001? Currently I can use the private IP of the ec2 host and define port 8001 ingress in the default kong security group. But ideally I wouldn't want to hunt down that private IP address for this service.

If it's acceptable to make the internal LB listen on port 8001 I will I can make a PR, but not sure if this is against the design of what you all want.

**Comment by miketwenty1** [comment]
@rlnchow ^

**Comment by DennoVonDiesel** [comment]
It was a mistake in the documentation that has since been corrected... we don't want to expose the admin API on community edition as it's not protected with RBAC. It is best in this case to ssh to a Kong node in the cluster and run against localhost:8001 to keep it protected from outside modification. I typically script this using the aws cli to obtain an IP address of one of the nodes using the tag key/value pairs related to the cluster.

**Comment by miketwenty1** [comment]
I'm currently running:
```
KONG=kong-$ENV
# searching for private ip of Kong for the specified env
aws ec2 describe-instances --region us-east-1 | jq -r --arg KONG $KONG '.Reservations[].Instances[].NetworkInterfaces[] | select(.Groups[].GroupName==$KONG) | .PrivateIpAddress' | head -n 1
```
To get the Ip for decK usage. I'd be curious if you would share what you are using to get the private IP. I'm guessing there's a better way.


In the case of a Kong node getting restarted and getting a new private IP. The service needing the admin port needs to be configured where it will re-run the script to get the new IP if fails/timeouts on the old one. 
Seems like an unnecessary pain. I assume this is what you're suggesting?

Is there a better way using the internal load balancer or another static pointer to Kong admin port for the free edition?

Going back to my idea..
We could make a flag that enables 8001 on the internal LB, but is defaulted false. 

Please let me know what you think @DennoVonDiesel I would like to make this solution more "immutable" without the idea of needing to restart or reconfigure services after they are spun up/kong nodes getting bounced. Interested to hear additional thoughts.

**Comment by DennoVonDiesel** [comment]
Say you keep the service name the default of "kong" and with an environment called "demo":

```
aws ec2 describe-instances \
    --filters "Name=tag:Name,Values=kong-demo" \
    --query 'Reservations[].Instances[].NetworkInterfaces[].PrivateIpAddress' \
    --output text
```

You can then pipe this to head -1 to get just one IP. I typically keep the kong configuration in a git repository and then on merge you can scp or pipe the config to deck on an active node. Happy to consider a PR that implements your flag toggled feature of the admin API being remotely available. I'd just want to update the README that it is clear anyone could access it from the VPC.

**Comment by miketwenty1** [comment]
@DennoVonDiesel 
https://github.com/Kong/kong-terraform-aws/pull/26

**Comment by miketwenty1** [comment]
closing issue I believe the proper way forward would be spin up a new load balancer specifically for the admin access that has its own security group, instead of meshing this with the currently existing internal load balancer.

**Comment by snabar** [comment]
@miketwenty1 do you have an example script of how you achieved the solution you mention here? I'm stuck on exactly this problem.

**Comment by miketwenty1** [comment]
@snabar 
https://github.com/miketwenty1/kong-terraform-aws/tree/newv2
You can see what I did here for reference. variables.tf has something called `enable_internal_admin_lb` flag
